insert into public.categories (slug, name, description, image_path, tint, sort_order) values
('mobiles-tablets', 'Mobiles & Tablets', 'Smartphones, tablets and the accessories that go with them.', '/images/demo/categories/mobiles-tablets.png', 'sky', 0),
('electronics-appliances', 'Electronics & Appliances', 'Audio, wearables, laptops and everyday appliances for home and work.', '/images/demo/categories/electronics-appliances.png', 'lavender', 1),
('fashion', 'Fashion', 'Clothing, footwear, bags and accessories for every day.', '/images/demo/categories/fashion.png', 'pink', 2),
('home-living', 'Home & Living', 'Cookware, decor and essentials that make a house feel like home.', '/images/demo/categories/home-living.png', 'mint', 3),
('beauty-personal-care', 'Beauty & Personal Care', 'Skincare, grooming and personal care picks.', '/images/demo/categories/beauty-personal-care.png', 'peach', 4),
('toys-games', 'Toys & Games', 'Toys, games and activity sets for kids of all ages.', '/images/demo/categories/toys-games.png', 'cream', 5),
('sports-outdoors', 'Sports & Outdoors', 'Shoes, fitness gear and outdoor essentials.', '/images/demo/categories/sports-outdoors.png', 'blue', 6),
('furniture', 'Furniture', 'Chairs, tables and storage for home and office.', '/images/demo/categories/furniture.png', 'lavender', 7)
on conflict (slug) do nothing;

insert into public.products (slug, title, brand, category_slug, short_description, description, price, mrp, rating, rating_count, image_path, pros, cons, is_top_pick, sku, stock) values
('mens-casual-sneakers', 'Men''s Casual Sneakers', 'Demo brand', 'fashion', 'Lightweight everyday sneakers with a cushioned sole.', 'Easy-to-style white sneakers for daily wear. The cushioned sole stays comfortable on long days, and the wipe-clean upper keeps them looking fresh.', 1299, 2499, 4.3, 12400, '/images/demo/products/mens-casual-sneakers.png', array['Comfortable cushioned sole', 'Goes with most outfits', 'Easy to clean']::text[], array['White shows dirt quickly', 'Runs slightly narrow']::text[], true, 'SE-FAS-001', 50),
('wireless-earbuds', 'Wireless Earbuds', 'Demo brand', 'electronics-appliances', 'True wireless earbuds with a compact charging case.', 'Pocket-sized earbuds for music and calls. They pair as soon as you open the case, and the case carries several extra charges for long days.', 1999, 3999, 4.4, 8900, '/images/demo/products/wireless-earbuds.png', array['Compact charging case', 'Quick pairing', 'Clear call quality']::text[], array['No active noise cancellation', 'Touch controls take practice']::text[], true, 'SE-ELE-002', 50),
('womens-handbag', 'Women''s Handbag', 'Demo brand', 'fashion', 'Structured handbag with room for daily essentials.', 'A structured everyday handbag with a roomy main compartment, an inner zip pocket and sturdy handles. Smart enough for work and easy to carry on weekends.', 1499, 2999, 4.2, 6100, '/images/demo/products/womens-handbag.png', array['Roomy main compartment', 'Sturdy handles', 'Works for office and outings']::text[], array['No shoulder strap', 'Light colour needs care']::text[], true, 'SE-FAS-003', 50),
('smart-watch', 'Smart Watch', 'Demo brand', 'electronics-appliances', 'Fitness smartwatch with a bright display and call alerts.', 'Tracks steps, sleep and workouts, and shows calls and messages on a bright square display. The battery lasts several days between charges.', 3999, 7999, 4.5, 15200, '/images/demo/products/smart-watch.png', array['Bright, easy-to-read display', 'Multi-day battery', 'Call and message alerts']::text[], array['Limited third-party apps', 'Proprietary charging cable']::text[], true, 'SE-ELE-004', 50),
('mens-t-shirt', 'Men''s T-Shirt', 'Demo brand', 'fashion', 'Soft cotton crew-neck T-shirt for everyday wear.', 'A regular-fit cotton T-shirt that works on its own or under a shirt. The fabric is soft and breathable, and the colour holds up well after washing.', 599, 1299, 4.1, 9800, '/images/demo/products/mens-t-shirt.png', array['Soft, breathable cotton', 'Regular fit', 'Holds colour after washing']::text[], array['May shrink slightly on first wash', 'Plain design']::text[], true, 'SE-FAS-005', 50),
('non-stick-cookware-set', 'Non-Stick Cookware Set', 'Demo brand', 'home-living', 'Non-stick pots and pans for everyday cooking.', 'A starter cookware set with a frying pan, kadai and saucepans. The non-stick coating needs less oil and makes cleaning quick.', 2499, 4999, 4.3, 4700, '/images/demo/products/non-stick-cookware-set.png', array['Needs less oil', 'Easy to clean', 'Covers everyday cooking']::text[], array['Not for metal spatulas', 'Coating wears with rough use']::text[], true, 'SE-HOM-006', 50),
('running-shoes', 'Running Shoes', 'Demo brand', 'sports-outdoors', 'Breathable running shoes with a grippy sole.', 'Lightweight running shoes with a breathable mesh upper and a cushioned midsole. The grippy outsole suits roads, tracks and the gym.', 2199, 4499, 4.2, 7300, '/images/demo/products/running-shoes.png', array['Breathable mesh upper', 'Cushioned midsole', 'Good grip']::text[], array['Not waterproof', 'Order half a size up']::text[], true, 'SE-SPO-007', 50),
('backpack', 'Backpack', 'Demo brand', 'sports-outdoors', 'Padded backpack with a laptop sleeve.', 'A roomy backpack for college, office or short trips. It has a padded laptop sleeve, a front organiser pocket and cushioned shoulder straps.', 1299, 2499, 4.2, 5600, '/images/demo/products/backpack.png', array['Padded laptop sleeve', 'Comfortable straps', 'Plenty of pockets']::text[], array['No rain cover included', 'Bulky when full']::text[], true, 'SE-SPO-008', 50),
('5g-smartphone', '5G Smartphone (8 GB RAM, 128 GB)', 'Demo brand', 'mobiles-tablets', 'Mid-range 5G phone with a large display and all-day battery.', 'A balanced mid-range phone with 5G, a large smooth display and a battery that lasts a full day. Fast charging gets it back up quickly.', 14999, 18999, 4.3, 21500, null, array['All-day battery', 'Smooth large display', 'Fast charging']::text[], array['Average low-light camera', 'Plastic back']::text[], false, 'SE-MOB-009', 50),
('android-tablet', '10-inch Android Tablet', 'Demo brand', 'mobiles-tablets', 'Large-screen tablet for classes, videos and reading.', 'A 10-inch tablet that suits online classes, streaming and reading. Dual speakers and a long-lasting battery make it a good family device.', 11999, 15999, 4.1, 3200, null, array['Large screen', 'Dual speakers', 'Long battery life']::text[], array['Not built for heavy gaming', 'Charges slowly']::text[], false, 'SE-MOB-010', 50),
('vitamin-c-face-serum', 'Vitamin C Face Serum', 'Demo brand', 'beauty-personal-care', 'Lightweight daily serum for brighter-looking skin.', 'A light, quick-absorbing serum for a daily skincare routine. It layers well under moisturiser and sunscreen.', 449, 699, 4.2, 5400, null, array['Absorbs quickly', 'Non-sticky', 'Layers well under sunscreen']::text[], array['Small bottle', 'Patch test needed for sensitive skin']::text[], false, 'SE-BEA-011', 50),
('hair-dryer', 'Hair Dryer (1200 W)', 'Demo brand', 'beauty-personal-care', 'Compact hair dryer with two heat settings.', 'A compact, foldable hair dryer with two heat settings and a cool-air option. Light enough to travel with and quick for everyday drying.', 899, 1499, 4, 2800, null, array['Foldable and light', 'Two heat settings', 'Dries quickly']::text[], array['A little noisy', 'Short power cord']::text[], false, 'SE-BEA-012', 50),
('remote-control-car', 'Remote Control Car', 'Demo brand', 'toys-games', 'Rechargeable remote control car for kids.', 'A sturdy, rechargeable remote control car with simple controls. It handles indoor floors and smooth outdoor surfaces.', 799, 1499, 4.1, 1900, null, array['Rechargeable battery', 'Simple controls', 'Sturdy build']::text[], array['Short play time per charge', 'Not for rough ground']::text[], false, 'SE-TOY-013', 50),
('building-blocks-set', 'Building Blocks Set (120 Pieces)', 'Demo brand', 'toys-games', 'Colourful building blocks for creative play.', 'A 120-piece set of colourful, chunky blocks that click together easily. It comes in a storage box and encourages creative play.', 599, 999, 4.4, 3600, null, array['Encourages creative play', 'Storage box included', 'Smooth, rounded edges']::text[], array['Small parts, not for toddlers', 'Box lid is loose']::text[], false, 'SE-TOY-014', 50),
('ergonomic-office-chair', 'Ergonomic Office Chair', 'Demo brand', 'furniture', 'Mesh-back office chair with lumbar support.', 'A mesh-back chair for long hours at a desk. It has adjustable height, lumbar support and a tilt mechanism, and the mesh keeps your back cool.', 5499, 9999, 4.2, 2300, null, array['Lumbar support', 'Breathable mesh back', 'Adjustable height and tilt']::text[], array['Needs assembly', 'Armrests are fixed']::text[], false, 'SE-FUR-015', 50),
('wooden-study-table', 'Wooden Study Table', 'Demo brand', 'furniture', 'Compact study table with a storage shelf.', 'A compact engineered-wood table for study or work from home. It has a shelf for books and fits comfortably in a small room.', 3999, 6999, 4, 1100, null, array['Fits small rooms', 'Storage shelf', 'Sturdy once assembled']::text[], array['Needs assembly', 'Surface scratches easily']::text[], false, 'SE-FUR-016', 50)
on conflict (slug) do nothing;

-- Keep the original catalogue order (products are listed oldest first).
update public.products p
set created_at = s.base + make_interval(secs => right(p.sku, 3)::int)
from (select min(created_at) as base from public.products) s;
