export const routes = {
  home: "/",
  /** The "Shop by Category" section of the home page. */
  allCategories: "/#categories",
  search: "/search",
  /** Products at or below a price, e.g. "Under ₹499". */
  searchUnder: (maxPrice: number) => `/search?maxPrice=${maxPrice}`,
  category: (slug: string) => `/category/${slug}`,
  product: (slug: string) => `/product/${slug}`,
  checkoutAddress: "/checkout/address",
  checkoutPayment: "/checkout/payment",
  checkoutSummary: "/checkout/summary",
  orderSuccess: "/checkout/success",
  orders: "/orders",
  orderDetails: (orderId: string) => `/orders/details?id=${encodeURIComponent(orderId)}`,
  account: "/account",
  /** The log in / register page, returning to `next` afterwards. */
  login: (next: string) => `/account?next=${encodeURIComponent(next)}`,
  admin: {
    login: "/admin/login",
    dashboard: "/admin",
    orders: "/admin/orders",
    order: (orderId: string) => `/admin/orders/${encodeURIComponent(orderId)}`,
    products: "/admin/products",
    newProduct: "/admin/products/new",
    product: (slug: string) => `/admin/products/${slug}`,
    inventory: "/admin/inventory",
    customers: "/admin/customers",
    coupons: "/admin/coupons",
    returns: "/admin/returns",
    reviews: "/admin/reviews",
    payments: "/admin/payments",
    settings: "/admin/settings",
  },
} as const;
