import type { Metadata } from "next";
import type { BreadcrumbItem } from "@/types";
import { siteConfig } from "./site-config";

const OPEN_GRAPH_LOCALE = "en_IN";
const SCHEMA_CONTEXT = "https://schema.org";

/** The image generated by app/opengraph-image.tsx. */
const DEFAULT_SHARE_IMAGE = {
  url: "/opengraph-image",
  width: 1200,
  height: 630,
  alt: `${siteConfig.name}: ${siteConfig.tagline}`,
};

export type JsonLdData = Record<string, unknown>;

interface PageMetadataOptions {
  title: string;
  description: string;
  /** The page's path, e.g. "/category/power-banks". Used for the canonical URL. */
  path: string;
  /** Use the title exactly as given instead of appending the site name. */
  absoluteTitle?: boolean;
  /** A page-specific sharing image. Pages without one use the site-wide Open Graph image. */
  image?: { url: string; alt: string };
  /** Keep the page out of search results while still letting crawlers follow its links. */
  noIndex?: boolean;
}

/** Turns a path into a full URL on the live site. */
export function absoluteUrl(path: string): string {
  return new URL(path, siteConfig.url).toString();
}

/** Builds the title, description, canonical URL and social sharing tags for a page. */
export function buildPageMetadata({
  title,
  description,
  path,
  absoluteTitle = false,
  image,
  noIndex = false,
}: PageMetadataOptions): Metadata {
  const socialTitle = absoluteTitle ? title : `${title} | ${siteConfig.name}`;
  const images = [image ?? DEFAULT_SHARE_IMAGE];

  return {
    title: absoluteTitle ? { absolute: title } : title,
    description,
    alternates: { canonical: path },
    openGraph: {
      type: "website",
      siteName: siteConfig.name,
      locale: OPEN_GRAPH_LOCALE,
      url: path,
      title: socialTitle,
      description,
      images,
    },
    twitter: {
      card: "summary_large_image",
      title: socialTitle,
      description,
      images,
    },
    robots: noIndex ? { index: false, follow: true } : undefined,
  };
}

export function organizationJsonLd(): JsonLdData {
  return {
    "@context": SCHEMA_CONTEXT,
    "@type": "Organization",
    name: siteConfig.name,
    url: absoluteUrl("/"),
    logo: absoluteUrl("/icon.svg"),
    description: siteConfig.description,
  };
}

/** Tells search engines the site's name, which they show above results. */
export function websiteJsonLd(): JsonLdData {
  return {
    "@context": SCHEMA_CONTEXT,
    "@type": "WebSite",
    name: siteConfig.name,
    url: absoluteUrl("/"),
  };
}

/**
 * Structured data for a breadcrumb trail.
 * `currentPath` is the page the trail ends on, used for the last item, which has no link.
 */
export function breadcrumbJsonLd(items: BreadcrumbItem[], currentPath: string): JsonLdData {
  return {
    "@context": SCHEMA_CONTEXT,
    "@type": "BreadcrumbList",
    itemListElement: items.map((item, index) => ({
      "@type": "ListItem",
      position: index + 1,
      name: item.label,
      item: absoluteUrl(item.href ?? currentPath),
    })),
  };
}
